/**
 * POST /api/discovery/roles — Discovery Mode step 3 (adjacent role surfacing).
 * GET  /api/discovery/roles?runId=… — read back the generated deck.
 *
 * STUB: roles are generated by Claude reasoning from general knowledge, not from
 * live job postings. See the TODO in lib/discovery/pipeline.ts — a real job
 * board data source has to replace this before production.
 *
 * TEST BUILD — gated behind the DISCOVERY_MODE flag.
 */

import { NextRequest, NextResponse } from 'next/server'
import { surfaceAdjacentRoles } from '@/lib/discovery/pipeline'
import { getIntake, getRoles, getSkillsMap, saveRoles } from '@/lib/discovery/store'
import { isDiscoveryEnabled, canAccessRun } from '@/lib/discovery/access'
import { checkRateLimit, getClientIp } from '@/lib/discovery/rate-limit'

export const runtime = 'nodejs'
export const maxDuration = 120

export async function POST(req: NextRequest): Promise<NextResponse> {
  if (!isDiscoveryEnabled()) return NextResponse.json({ error: 'Not found' }, { status: 404 })

  const { runId } = (await req.json()) as { runId?: string }
  if (!runId || !(await canAccessRun(runId))) {
    return NextResponse.json({ error: 'Not found' }, { status: 404 })
  }

  try {
    // Idempotent, and re-entering the swipe deck must not discard reactions.
    const existing = await getRoles(runId)
    if (existing.length > 0) return NextResponse.json({ roles: existing, stubbed: true })

    const [intake, functions] = await Promise.all([getIntake(runId), getSkillsMap(runId)])
    if (!intake) return NextResponse.json({ error: 'Not found' }, { status: 404 })
    if (!functions) {
      return NextResponse.json({ error: 'Generate the skills map first.' }, { status: 409 })
    }

    const rate = await checkRateLimit(getClientIp(req), 'roles')
    if (!rate.allowed) {
      return NextResponse.json({ error: 'Too many requests — try again later.' }, { status: 429 })
    }

    const roles = await surfaceAdjacentRoles(runId, functions, intake.selections, intake.otherNotes)
    await saveRoles(runId, roles)
    return NextResponse.json({ roles, stubbed: true })
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err)
    console.error('[/api/discovery/roles]', message)
    return NextResponse.json({ error: message }, { status: 500 })
  }
}

export async function GET(req: NextRequest): Promise<NextResponse> {
  if (!isDiscoveryEnabled()) return NextResponse.json({ error: 'Not found' }, { status: 404 })

  const runId = req.nextUrl.searchParams.get('runId')
  if (!runId || !(await canAccessRun(runId))) {
    return NextResponse.json({ error: 'Not found' }, { status: 404 })
  }

  return NextResponse.json({ roles: await getRoles(runId), stubbed: true })
}
