/**
 * Discovery Mode LLM stages — TEST BUILD.
 *
 * Mirrors the forced-tool_use pattern in lib/pipeline.ts and uses the same
 * Claude model, so Discovery behaves like the rest of the app. Claude-only —
 * the Grok fallback in the main pipeline isn't wired up here.
 */

import Anthropic from '@anthropic-ai/sdk'
import type { Tool as AnthropicTool } from '@anthropic-ai/sdk/resources/messages/messages'
import {
  SKILLS_MAP_TOOL,
  buildSkillsMapPrompt,
  ADJACENT_ROLES_TOOL,
  buildAdjacentRolesPrompt,
  ROLE_COMPARISON_TOOL,
  buildRoleComparisonPrompt,
} from './prompts'
import type { FunctionalSkill, IntakeSelections, DiscoveryRole, RoleComparisonEnrichment } from './types'

// Same model the main pipeline uses — keep these in sync.
const CLAUDE_MODEL = 'claude-sonnet-4-6'

function getClient(): Anthropic {
  const key = process.env.ANTHROPIC_API_KEY
  if (!key) throw new Error('ANTHROPIC_API_KEY is not set.')
  return new Anthropic({ apiKey: key })
}

async function callClaude<T>(tool: AnthropicTool, prompt: string, maxTokens: number): Promise<T> {
  const response = await getClient().messages.create({
    model: CLAUDE_MODEL,
    max_tokens: maxTokens,
    tools: [tool],
    tool_choice: { type: 'tool', name: tool.name },
    messages: [{ role: 'user', content: prompt }],
  })
  const block = response.content.find((b) => b.type === 'tool_use')
  if (!block || block.type !== 'tool_use') {
    throw new Error(
      `Claude did not call the expected tool. Response: ${JSON.stringify(response.content).slice(0, 500)}`,
    )
  }
  return block.input as T
}

// ─── Step 2 ───────────────────────────────────────────────────────────────────

export async function extractSkillsMap(
  selections: IntakeSelections,
  otherNotes: string | null,
): Promise<FunctionalSkill[]> {
  const out = await callClaude<{ functions: FunctionalSkill[] }>(
    SKILLS_MAP_TOOL as AnthropicTool,
    buildSkillsMapPrompt(selections, otherNotes),
    2048,
  )
  return out.functions
}

// ─── Step 3 ───────────────────────────────────────────────────────────────────

/**
 * TODO (blocks production): roles here are generated by Claude reasoning from
 * general knowledge — they are plausible, not sourced from live postings. Before
 * this ships, swap this for a real job-board data source (Adzuna / Reed / an
 * internal cached posting set) and have Claude rank/annotate *real* listings
 * rather than inventing role titles. The swipe deck in step 4 should then show
 * actual postings, which is what the spec calls for. See also lib/jobs/ for the
 * job-matching code the main pivot flow already uses.
 */
export async function surfaceAdjacentRoles(
  runId: string,
  functions: FunctionalSkill[],
  selections: IntakeSelections,
  otherNotes: string | null,
): Promise<DiscoveryRole[]> {
  const out = await callClaude<{ roles: Omit<DiscoveryRole, 'id' | 'runId' | 'rank'>[] }>(
    ADJACENT_ROLES_TOOL as AnthropicTool,
    buildAdjacentRolesPrompt(functions, selections, otherNotes),
    4096,
  )
  return out.roles.map((r, i) => ({
    ...r,
    id: `${runId}:${i}`,
    runId,
    rank: i,
  }))
}

// ─── Bridge: shortlist comparison ─────────────────────────────────────────────

/**
 * TODO (blocks production): entry-barrier and demand content is Claude
 * reasoning, not real market data — see the TODO on ROLE_COMPARISON_TOOL in
 * prompts.ts. Also NOT persisted: the caller regenerates this on every visit
 * to the comparison screen rather than caching it in Postgres, which is an
 * acceptable simplification for a test build but a re-cost if this survives
 * into production traffic.
 */
export async function enrichShortlistForComparison(
  roles: DiscoveryRole[],
  functions: FunctionalSkill[],
): Promise<Record<string, RoleComparisonEnrichment>> {
  if (roles.length === 0) return {}
  // Up to 10 roles × (dayToDay + entryBarrier + demandNote) needs real headroom —
  // 2048 truncated mid-response for a 6-role shortlist and left `roles` missing
  // from the parsed tool input entirely.
  const out = await callClaude<{ roles?: ({ roleId: string } & RoleComparisonEnrichment)[] }>(
    ROLE_COMPARISON_TOOL as AnthropicTool,
    buildRoleComparisonPrompt(roles, functions),
    6144,
  )
  // This content is a nice-to-have (see the TODO above) — degrade to "no
  // enrichment" rather than 500ing the whole comparison screen if the model
  // ever returns a shape we don't expect.
  if (!Array.isArray(out.roles)) return {}
  return Object.fromEntries(
    out.roles.map(({ roleId, dayToDay, entryBarrier, demandNote }) => [
      roleId,
      { dayToDay, entryBarrier, demandNote },
    ]),
  )
}
