/**
 * Discovery Mode types — TEST BUILD (see /discovery-test).
 *
 * Kept separate from lib/types.ts so nothing in the main pivot flow depends on
 * this feature while it's behind the test flag.
 */

// ─── Step 1: evidence intake ──────────────────────────────────────────────────

/**
 * A single selectable pointer chip. `signal` is a hidden mapping to a likely
 * functional-skill hint — it never renders in the UI, but it means Step 2 has
 * structured signal to reason from even before any free text is written.
 *
 * Chip ids are persisted (as part of a stored intake run), so treat them as
 * stable once shipped — add new chips freely, but don't repurpose an id.
 */
export interface ChipOption {
  id: string
  label: string
  /** A likely functional-skill hint, e.g. "systems thinking" — a pointer for Claude, not a verdict. */
  signal: string
}

export interface PromptBank {
  id: string
  /** The question as shown to the user — deliberately evidence-based, never aspirational. */
  prompt: string
  chips: ChipOption[]
}

/** A chip the user tapped, plus their optional one-line example for it. */
export interface SelectedChip {
  chipId: string
  note?: string
}

/** Keyed by PromptBank.id. */
export type IntakeSelections = Record<string, SelectedChip[]>

export interface DiscoveryIntake {
  id: string
  userId: string | null
  selections: IntakeSelections
  /** The final open "anything else?" field — always optional. */
  otherNotes: string | null
  createdAt: string
}

// ─── Step 2: functional skills map ────────────────────────────────────────────

export interface FunctionalSkill {
  /** A functional capability — e.g. "systems thinking", never a job title. */
  name: string
  /** One line on what this looks like in their case. */
  summary: string
  /** Quotes or close paraphrases from their own intake answers. */
  evidence: string[]
}

export interface SkillsMap {
  runId: string
  functions: FunctionalSkill[]
}

// ─── Step 3: adjacent roles ───────────────────────────────────────────────────

/** One real, live UK posting — from Adzuna, via lib/discovery/postings.ts. */
export interface RolePosting {
  title: string
  employer: string
  location: string
  url: string
  salaryMin: number | null
  salaryMax: number | null
}

export interface DiscoveryRole {
  id: string
  runId: string
  /** Original suggestion order — the tiebreaker when ranking the shortlist. */
  rank: number
  /** The real, searchable job title as it appears in postings. */
  title: string
  industry: string
  /**
   * One plain-language sentence on what the role actually involves day-to-day,
   * in everyday, non-corporate language — so an unfamiliar-sounding title
   * (e.g. "Implementation Consultant") doesn't cause someone to bounce off a
   * genuinely good-fit role. Shown prominently right under the title, not
   * buried — this is a standing principle for any role-surfacing UI, not just
   * this card (see the PRD).
   */
  plainLanguageLine: string
  whyFits: string
  /** Which of their functional skills transfer directly. */
  functionsUsed: string[]
  /** One honest gap or translation challenge. Not oversold. */
  gap: string
  /**
   * Real-world grounding for a title Claude proposed — how many live UK
   * postings currently match it, via Adzuna (lib/discovery/postings.ts). Null
   * when Adzuna isn't configured or the lookup failed — never a fabricated
   * number. Zero is a real, meaningful answer (the title may be too narrow or
   * genuinely rare) and is shown as such, not hidden.
   */
  postingCount: number | null
  /** Up to 3 real sample postings for this title, if any were found. */
  samplePostings: RolePosting[]
}

// ─── Step 4: reactions + shortlist ────────────────────────────────────────────

export type Reaction = 'like' | 'pass' | 'unsure'

export interface DiscoveryReaction {
  runId: string
  roleId: string
  reaction: Reaction
}

export interface ShortlistEntry {
  role: DiscoveryRole
  reaction: Reaction
}

// ─── Bridge: shortlist comparison → single target commitment ─────────────────
// (Persona A finishes the swipe deck here; Persona B skips everything above
// and lands directly in the commitment step via /target-role.)

/**
 * Stub content generated by Claude reasoning, not live market data — see the
 * TODO in lib/discovery/pipeline.ts. Not persisted: regenerated each time the
 * comparison screen loads.
 */
export interface RoleComparisonEnrichment {
  dayToDay: string
  entryBarrier: string
  demandNote: string
}

export type CommitmentSource = 'discovery' | 'direct'

export interface TargetCommitment {
  id: string
  userId: string | null
  /** Set for Persona A (sourced from a Discovery Mode run); null for Persona B. */
  runId: string | null
  /** Set for Persona A (which shortlisted role); null for Persona B. */
  roleId: string | null
  source: CommitmentSource
  roleTitle: string
  /** Copied from the chosen role for Persona A; null for Persona B's free text. */
  plainLanguageLine: string | null
  committedAt: string
}
