export const INDUSTRIES = [
  'Technology',
  'Healthcare',
  'Finance',
  'Education',
  'Media & Marketing',
  'Consulting',
  'Retail & E-commerce',
  'Manufacturing & Supply Chain',
  'Energy & Sustainability',
  'Legal',
  'Non-profit',
  'Government',
] as const

export const FUNCTIONS: Record<string, string[]> = {
  Technology: ['Product', 'Project & Delivery', 'Engineering', 'Design', 'Data & Analytics', 'Operations', 'People & HR', 'Sales & GTM'],
  Healthcare: ['Clinical Operations', 'Project & Delivery', 'Health Informatics', 'Product & Technology', 'Research & Clinical Trials'],
  Finance: ['FinTech Product', 'Project & Delivery', 'Risk & Compliance', 'Operations', 'Investment & Analysis'],
  Education: ['EdTech', 'Project & Delivery', 'Learning & Development', 'Curriculum & Instruction', 'Administration'],
  'Media & Marketing': ['Content Strategy', 'Project & Delivery', 'Brand & Marketing', 'Growth & Performance', 'Communications'],
  Consulting: ['Strategy', 'Project & Delivery', 'Operations', 'Technology', 'People & Org'],
  'Retail & E-commerce': ['E-commerce & Digital', 'Project & Delivery', 'Merchandising & Buying', 'Supply Chain & Operations', 'Marketing'],
  'Manufacturing & Supply Chain': ['Operations', 'Project & Delivery', 'Supply Chain & Logistics', 'Quality & Process', 'Engineering'],
  'Energy & Sustainability': ['Sustainability & ESG', 'Project & Delivery', 'Operations', 'Policy & Strategy'],
  Legal: ['Legal Operations', 'Project & Delivery', 'Compliance', 'Contracts & Commercial'],
  'Non-profit': ['Programs', 'Project & Delivery', 'Operations', 'Development & Fundraising', 'Policy & Advocacy'],
  Government: ['Policy', 'Project & Delivery', 'Digital Services', 'Operations', 'Research & Analysis'],
}

export const ROLES: Record<string, Record<string, string[]>> = {
  Technology: {
    Product: [
      'Product Manager',
      'Associate Product Manager',
      'Senior Product Manager',
      'Group Product Manager',
      'Product Operations Manager',
      'Technical Product Manager',
    ],
    'Project & Delivery': [
      'Technical Project Manager',
      'Project Manager',
      'Delivery Manager',
      'Scrum Master',
      'Agile Delivery Lead',
      'Programme Manager',
      'PMO Analyst',
      'Implementation Manager',
    ],
    Engineering: ['Software Engineer', 'Engineering Manager', 'Technical Lead', 'Staff Engineer'],
    Design: ['Product Designer', 'UX Designer', 'UX Researcher', 'Design Manager'],
    'Data & Analytics': ['Data Analyst', 'Data Scientist', 'Analytics Engineer', 'Business Intelligence Analyst'],
    Operations: ['Operations Manager', 'Business Operations Analyst', 'Chief of Staff', 'Strategy & Ops Manager'],
    'People & HR': ['People Operations Manager', 'Talent Acquisition Partner', 'HR Business Partner', 'L&D Manager'],
    'Sales & GTM': ['Solutions Engineer', 'Customer Success Manager', 'Account Executive'],
  },
  Healthcare: {
    'Clinical Operations': ['Clinical Operations Manager', 'Care Coordinator', 'Quality Improvement Specialist'],
    'Project & Delivery': [
      'Healthcare Project Manager',
      'Clinical Programme Manager',
      'Service Improvement Manager',
      'Implementation Manager',
      'Transformation Project Manager',
      'PMO Analyst',
    ],
    'Health Informatics': ['Clinical Informatics Analyst', 'Health Data Analyst', 'EHR Implementation Specialist'],
    'Product & Technology': ['Health Tech Product Manager', 'Digital Health Product Manager'],
    'Research & Clinical Trials': ['Clinical Research Coordinator', 'Research Operations Manager'],
  },
  Finance: {
    'FinTech Product': ['FinTech Product Manager', 'Payments Product Manager', 'Banking Product Manager'],
    'Project & Delivery': [
      'Financial Services Project Manager',
      'Change Delivery Manager',
      'Business Change Manager',
      'Programme Manager',
      'PMO Analyst',
    ],
    'Risk & Compliance': ['Risk Analyst', 'Compliance Manager'],
    Operations: ['Financial Operations Analyst', 'Treasury Analyst'],
    'Investment & Analysis': ['Investment Analyst', 'Portfolio Analyst'],
  },
  Education: {
    EdTech: ['EdTech Product Manager', 'Learning Experience Designer', 'Curriculum Designer'],
    'Project & Delivery': ['Education Project Manager', 'Programme Manager', 'Implementation Manager', 'Project Coordinator'],
    'Learning & Development': ['L&D Specialist', 'Training Manager', 'Instructional Designer'],
    'Curriculum & Instruction': ['Curriculum Developer', 'Academic Coordinator'],
    Administration: ['Academic Program Manager', 'Registrar'],
  },
  'Media & Marketing': {
    'Content Strategy': ['Content Strategist', 'Editorial Manager', 'Content Operations Manager'],
    'Project & Delivery': ['Marketing Project Manager', 'Campaign Delivery Manager', 'Production Manager', 'Account Manager'],
    'Brand & Marketing': ['Marketing Manager', 'Brand Manager', 'Campaign Manager'],
    'Growth & Performance': ['Growth Manager', 'Performance Marketing Manager', 'CRO Specialist'],
    Communications: ['Communications Manager', 'PR Manager', 'Internal Communications Manager'],
  },
  Consulting: {
    Strategy: ['Strategy Consultant', 'Management Consultant', 'Senior Associate'],
    'Project & Delivery': ['Project Manager', 'Engagement Manager', 'Delivery Lead', 'PMO Consultant', 'Programme Manager'],
    Operations: ['Operations Consultant', 'Process Improvement Analyst'],
    Technology: ['Technology Consultant', 'IT Consultant'],
    'People & Org': ['Organisational Design Consultant', 'Change Management Consultant'],
  },
  'Retail & E-commerce': {
    'E-commerce & Digital': ['E-commerce Manager', 'Digital Product Manager', 'Online Trading Manager', 'Marketplace Manager'],
    'Project & Delivery': ['Retail Project Manager', 'Programme Manager', 'Implementation Manager', 'PMO Analyst'],
    'Merchandising & Buying': ['Merchandiser', 'Buyer', 'Category Manager', 'Planning Manager'],
    'Supply Chain & Operations': ['Operations Manager', 'Logistics Manager', 'Store Operations Manager'],
    Marketing: ['Retail Marketing Manager', 'CRM Manager', 'Brand Manager'],
  },
  'Manufacturing & Supply Chain': {
    Operations: ['Operations Manager', 'Plant Manager', 'Production Manager'],
    'Project & Delivery': ['Manufacturing Project Manager', 'Programme Manager', 'Continuous Improvement Manager', 'PMO Analyst'],
    'Supply Chain & Logistics': ['Supply Chain Manager', 'Logistics Manager', 'Procurement Manager', 'Demand Planner'],
    'Quality & Process': ['Quality Manager', 'Process Engineer', 'Lean / Six Sigma Specialist'],
    Engineering: ['Manufacturing Engineer', 'Industrial Engineer', 'Maintenance Manager'],
  },
  'Energy & Sustainability': {
    'Sustainability & ESG': ['Sustainability Manager', 'ESG Analyst', 'Carbon / Net-Zero Lead', 'Environmental Manager'],
    'Project & Delivery': ['Renewables Project Manager', 'Programme Manager', 'Project Engineer', 'PMO Analyst'],
    Operations: ['Operations Manager', 'Asset Manager', 'Energy Analyst'],
    'Policy & Strategy': ['Energy Policy Analyst', 'Strategy Manager', 'Regulatory Affairs Manager'],
  },
  Legal: {
    'Legal Operations': ['Legal Operations Manager', 'Legal Project Manager', 'Knowledge Manager'],
    'Project & Delivery': ['Legal Project Manager', 'Programme Manager', 'Change Manager', 'PMO Analyst'],
    Compliance: ['Compliance Manager', 'Compliance Analyst', 'Data Protection Officer'],
    'Contracts & Commercial': ['Contracts Manager', 'Commercial Manager', 'Paralegal'],
  },
  'Non-profit': {
    Programs: ['Program Manager', 'Program Director', 'Program Coordinator'],
    'Project & Delivery': ['Project Manager', 'Programme Manager', 'Project Coordinator', 'Delivery Manager'],
    Operations: ['Operations Manager', 'COO'],
    'Development & Fundraising': ['Development Manager', 'Grant Writer', 'Major Gifts Officer'],
    'Policy & Advocacy': ['Policy Analyst', 'Advocacy Manager'],
  },
  Government: {
    Policy: ['Policy Analyst', 'Policy Advisor', 'Legislative Analyst'],
    'Project & Delivery': ['Project Manager', 'Programme Manager', 'Delivery Manager', 'PMO Lead', 'Project Coordinator'],
    'Digital Services': ['Digital Transformation Manager', 'Government Product Manager'],
    Operations: ['Operations Manager', 'Programme Manager'],
    'Research & Analysis': ['Research Analyst', 'Evaluation Specialist'],
  },
}
