import Link from 'next/link'
import { Logo } from '@/components/brand'

export const metadata = {
  title: 'Terms of Service — PivotPath',
  description: 'The terms governing your use of PivotPath.',
}

const LAST_UPDATED = '24 June 2026'

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-navy">
      <header className="border-b" style={{ borderColor: 'rgba(242,237,228,0.1)' }}>
        <div className="max-w-pp-content mx-auto px-7 py-4 flex items-center justify-between">
          <Link href="/" aria-label="PivotPath home"><Logo size="sm" /></Link>
          <Link href="/legal/privacy" className="text-[13.5px] text-pp-text-faint hover:text-pp-text-muted transition-colors">
            Privacy policy
          </Link>
        </div>
      </header>

      <main className="max-w-[720px] mx-auto px-6 py-14">
        <p className="font-mono text-[11px] tracking-[0.1em] uppercase text-amber mb-3">Legal</p>
        <h1 className="font-display text-[36px] font-medium text-offwhite mb-2">Terms of Service</h1>
        <p className="text-[13.5px] text-pp-text-ghost mb-12">Last updated: {LAST_UPDATED}</p>

        <div className="prose-pp space-y-10 text-[15px] leading-[1.75] text-pp-text-body">

          <section>
            <h2>1. Acceptance</h2>
            <p>
              By creating an account or using PivotPath (&quot;the Service&quot;), you agree to these Terms of Service.
              If you do not agree, do not use the Service. These terms form a binding agreement between you
              and PivotPath.
            </p>
          </section>

          <section>
            <h2>2. What PivotPath does</h2>
            <p>
              PivotPath is an AI-assisted career transition tool. It analyses your career background and
              generates a Translation Map (skill transferability), rewritten resume content, and a career
              strategy brief for transitioning into a target role.
            </p>
            <p>
              <strong>Important:</strong> Outputs are AI-generated suggestions, not professional career advice.
              They should be treated as a starting point for your own research and judgment, not as definitive
              guidance. PivotPath does not guarantee employment outcomes.
            </p>
          </section>

          <section>
            <h2>3. Your account</h2>
            <ul>
              <li>You must be at least 16 years old to create an account.</li>
              <li>You are responsible for maintaining the security of your account credentials.</li>
              <li>You must not share your account with others.</li>
              <li>You must provide accurate information when registering.</li>
              <li>We may suspend or terminate accounts that violate these terms.</li>
            </ul>
          </section>

          <section>
            <h2>4. Acceptable use</h2>
            <p>You agree not to:</p>
            <ul>
              <li>Use the Service to generate content that is fraudulent, misleading, or intended to deceive employers or recruiters.</li>
              <li>Upload content that infringes third-party intellectual property rights.</li>
              <li>Attempt to reverse-engineer, scrape, or access the Service through automated means.</li>
              <li>Use the Service in a way that violates any applicable law or regulation.</li>
              <li>Submit malicious content or attempt to compromise the security of the platform.</li>
            </ul>
          </section>

          <section>
            <h2>5. Your content</h2>
            <p>
              You retain ownership of the CV text and career information you submit. By submitting it,
              you grant PivotPath a limited, non-exclusive licence to process it for the sole purpose of
              providing the analysis Service to you. We do not use your content to train AI models.
            </p>
          </section>

          <section>
            <h2>6. AI-generated outputs</h2>
            <p>
              Analysis outputs (Translation Maps, resume content, strategy briefs) are generated by AI and
              are provided &quot;as is&quot; without warranty of accuracy or fitness for a particular purpose.
              You are solely responsible for how you use these outputs, including any claims made to
              prospective employers.
            </p>
            <p>
              PivotPath is not liable for any employment decisions, missed opportunities, or other
              consequences resulting from reliance on AI-generated content.
            </p>
          </section>

          <section>
            <h2>7. Free tier and fair use</h2>
            <p>
              The free tier grants access to the core pivot analysis features. We reserve the right to
              apply rate limits or introduce paid tiers for heavy usage. We will give reasonable notice of
              any material changes to access or pricing.
            </p>
          </section>

          <section>
            <h2>8. Availability and changes</h2>
            <p>
              We aim to keep PivotPath available but do not guarantee uninterrupted access. We may modify,
              suspend, or discontinue features at any time. For material changes that affect existing users,
              we will provide at least 14 days&apos; notice where reasonably practicable.
            </p>
          </section>

          <section>
            <h2>9. Intellectual property</h2>
            <p>
              The PivotPath brand, logo, design, and software are our intellectual property. Nothing in
              these terms transfers ownership of any PivotPath intellectual property to you.
            </p>
          </section>

          <section>
            <h2>10. Limitation of liability</h2>
            <p>
              To the maximum extent permitted by applicable law, PivotPath shall not be liable for any
              indirect, incidental, special, consequential, or punitive damages arising from your use of
              the Service. Our total liability for any claim arising from use of the Service shall not
              exceed the amount you paid us in the 12 months prior to the claim (or £50 if no payment was made).
            </p>
            <p>
              Nothing in these terms limits our liability for death or personal injury caused by negligence,
              fraud, or any other liability that cannot be excluded under English law.
            </p>
          </section>

          <section>
            <h2>11. Data protection</h2>
            <p>
              Our collection and use of your personal data is governed by our{' '}
              <Link href="/legal/privacy" className="text-amber hover:text-amber/80">Privacy Policy</Link>,
              which forms part of these terms. We comply with the UK GDPR and the Data Protection Act 2018.
            </p>
          </section>

          <section>
            <h2>12. Governing law</h2>
            <p>
              These terms are governed by the laws of England and Wales. Any disputes shall be subject
              to the exclusive jurisdiction of the courts of England and Wales.
            </p>
          </section>

          <section>
            <h2>13. Changes to these terms</h2>
            <p>
              We may update these terms from time to time. We will notify you by email at least 14 days
              before material changes take effect. Continuing to use the Service after changes take effect
              constitutes acceptance of the updated terms.
            </p>
          </section>

          <section>
            <h2>14. Contact</h2>
            <p>
              Questions about these terms? Email us at{' '}
              <a href="mailto:legal@pivotpath.co">legal@pivotpath.co</a>.
            </p>
          </section>

        </div>

        <div className="mt-16 flex flex-wrap gap-5 text-[13px] text-pp-text-ghost border-t pt-8" style={{ borderColor: 'rgba(242,237,228,0.1)' }}>
          <Link href="/" className="hover:text-pp-text-faint transition-colors">← Back to PivotPath</Link>
          <Link href="/legal/privacy" className="hover:text-pp-text-faint transition-colors">Privacy policy</Link>
          <Link href="/settings" className="hover:text-pp-text-faint transition-colors">Settings</Link>
        </div>
      </main>
    </div>
  )
}
